### ISSUE TITLE
document using egress-ip in ROSA OVN clusters

### ISSUE THREAD

**Issue by paulczar** [rh-mobb/documentation#289]
```
cat <<EOF | oc apply -f -
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egress-demo
spec:
  egressIPs:
  - 10.0.192.69
  - 10.0.128.69
  - 10.0.160.69    
  namespaceSelector:
    matchLabels:
      env: egressip
---
apiVersion: v1
kind: Namespace
metadata:
  name: egress-demo
  labels:
    env: egressip
EOF
 rosa update machinepool -c pczarkow-sts \
   --labels "k8s.ovn.org/egress-assignable=" Default
```
